# Generated by Django 5.0.6 on 2024-07-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemodule', '0003_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
